[2023-02-21 11:38:16,345] {processor.py:163} INFO - Started process (PID=46) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2023-02-21 11:38:16,356] {processor.py:642} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2023-02-21 11:38:16,363] {logging_mixin.py:109} INFO - [2023-02-21 11:38:16,362] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2023-02-21 11:38:21,356] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2023-02-21 11:38:21,759] {logging_mixin.py:109} INFO - [2023-02-21 11:38:21,758] {dag.py:2396} INFO - Sync 1 DAGs
[2023-02-21 11:38:21,795] {processor.py:171} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 5.510 seconds
[2023-02-21 11:38:51,909] {processor.py:163} INFO - Started process (PID=65) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2023-02-21 11:38:51,913] {processor.py:642} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2023-02-21 11:38:51,919] {logging_mixin.py:109} INFO - [2023-02-21 11:38:51,919] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2023-02-21 11:38:53,966] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2023-02-21 11:38:54,012] {logging_mixin.py:109} INFO - [2023-02-21 11:38:54,010] {dag.py:2396} INFO - Sync 1 DAGs
[2023-02-21 11:38:54,195] {processor.py:171} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 2.290 seconds
[2023-02-21 11:39:24,500] {processor.py:163} INFO - Started process (PID=86) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2023-02-21 11:39:24,503] {processor.py:642} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2023-02-21 11:39:24,507] {logging_mixin.py:109} INFO - [2023-02-21 11:39:24,507] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2023-02-21 11:39:26,999] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2023-02-21 11:39:27,041] {logging_mixin.py:109} INFO - [2023-02-21 11:39:27,040] {dag.py:2396} INFO - Sync 1 DAGs
[2023-02-21 11:39:27,139] {processor.py:171} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 2.651 seconds
[2023-02-21 11:39:57,569] {processor.py:163} INFO - Started process (PID=107) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2023-02-21 11:39:57,580] {processor.py:642} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2023-02-21 11:39:57,587] {logging_mixin.py:109} INFO - [2023-02-21 11:39:57,586] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2023-02-21 11:40:00,965] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2023-02-21 11:40:01,065] {logging_mixin.py:109} INFO - [2023-02-21 11:40:01,064] {dag.py:2396} INFO - Sync 1 DAGs
[2023-02-21 11:40:01,276] {processor.py:171} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 3.723 seconds
[2023-02-21 11:40:32,141] {processor.py:163} INFO - Started process (PID=128) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2023-02-21 11:40:32,157] {processor.py:642} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2023-02-21 11:40:32,163] {logging_mixin.py:109} INFO - [2023-02-21 11:40:32,162] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2023-02-21 11:40:39,339] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2023-02-21 11:40:39,388] {logging_mixin.py:109} INFO - [2023-02-21 11:40:39,387] {dag.py:2396} INFO - Sync 1 DAGs
[2023-02-21 11:40:39,543] {processor.py:171} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 7.612 seconds
[2023-02-21 11:41:10,032] {processor.py:163} INFO - Started process (PID=139) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2023-02-21 11:41:10,068] {processor.py:642} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2023-02-21 11:41:10,080] {logging_mixin.py:109} INFO - [2023-02-21 11:41:10,075] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2023-02-21 11:41:40,116] {logging_mixin.py:109} INFO - [2023-02-21 11:41:40,115] {timeout.py:36} ERROR - Process timed out, PID: 139
[2023-02-21 11:41:40,623] {logging_mixin.py:109} INFO - [2023-02-21 11:41:40,197] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 10, in <module>
    from airflow.providers.google.cloud.operators.bigquery import BigQueryCreateExternalTableOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 38, in <module>
    from airflow.providers.google.cloud.hooks.bigquery import BigQueryHook, BigQueryJob
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 57, in <module>
    from airflow.providers.google.common.hooks.base_google import GoogleBaseHook
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 45, in <module>
    from airflow.providers.google.cloud.utils.credentials_provider import (
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 36, in <module>
    from airflow.providers.google.cloud._internal_client.secret_manager_client import _SecretManagerClient
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/_internal_client/secret_manager_client.py", line 29, in <module>
    from google.cloud.secretmanager_v1 import SecretManagerServiceClient
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/secretmanager_v1/__init__.py", line 24, in <module>
    from google.cloud.secretmanager_v1.gapic import secret_manager_service_client
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/secretmanager_v1/gapic/secret_manager_service_client.py", line 36, in <module>
    from google.cloud.secretmanager_v1.gapic.transports import (
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/data_ingestion_gcs_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 139
[2023-02-21 11:41:41,370] {processor.py:690} INFO - Deactivated 1 DAGs which are no longer present in /opt/airflow/dags/data_ingestion_gcs_dag.py
[2023-02-21 11:41:41,397] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2023-02-21 11:41:41,832] {processor.py:171} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 31.844 seconds
[2023-02-21 11:42:15,840] {processor.py:163} INFO - Started process (PID=175) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2023-02-21 11:42:16,108] {processor.py:642} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2023-02-21 11:42:16,149] {logging_mixin.py:109} INFO - [2023-02-21 11:42:16,149] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2023-02-21 11:42:46,330] {logging_mixin.py:109} INFO - [2023-02-21 11:42:46,287] {timeout.py:36} ERROR - Process timed out, PID: 175
[2023-02-21 11:42:46,917] {logging_mixin.py:109} INFO - [2023-02-21 11:42:46,546] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 10, in <module>
    from airflow.providers.google.cloud.operators.bigquery import BigQueryCreateExternalTableOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 38, in <module>
    from airflow.providers.google.cloud.hooks.bigquery import BigQueryHook, BigQueryJob
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 33, in <module>
    from google.cloud.bigquery import (
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/__init__.py", line 35, in <module>
    from google.cloud.bigquery.client import Client
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 61, in <module>
    from google.cloud.bigquery_storage_v1.services.big_query_read.client import (
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery_storage_v1/__init__.py", line 25, in <module>
    from google.cloud.bigquery_storage_v1 import client
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery_storage_v1/client.py", line 26, in <module>
    from google.cloud.bigquery_storage_v1 import reader
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery_storage_v1/reader.py", line 28, in <module>
    import pandas
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 63, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "<frozen importlib._bootstrap>", line 194, in _lock_unlock_module
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/data_ingestion_gcs_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 175
[2023-02-21 11:42:47,201] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2023-02-21 11:42:47,373] {processor.py:171} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 32.099 seconds
[2023-02-21 11:43:19,827] {processor.py:163} INFO - Started process (PID=204) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2023-02-21 11:43:19,855] {processor.py:642} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2023-02-21 11:43:19,869] {logging_mixin.py:109} INFO - [2023-02-21 11:43:19,868] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2023-02-21 11:43:50,282] {logging_mixin.py:109} INFO - [2023-02-21 11:43:50,182] {timeout.py:36} ERROR - Process timed out, PID: 204
[2023-02-21 11:43:50,738] {logging_mixin.py:109} INFO - [2023-02-21 11:43:50,423] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 10, in <module>
    from airflow.providers.google.cloud.operators.bigquery import BigQueryCreateExternalTableOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 38, in <module>
    from airflow.providers.google.cloud.hooks.bigquery import BigQueryHook, BigQueryJob
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 33, in <module>
    from google.cloud.bigquery import (
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/__init__.py", line 35, in <module>
    from google.cloud.bigquery.client import Client
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 61, in <module>
    from google.cloud.bigquery_storage_v1.services.big_query_read.client import (
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery_storage_v1/__init__.py", line 25, in <module>
    from google.cloud.bigquery_storage_v1 import client
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery_storage_v1/client.py", line 26, in <module>
    from google.cloud.bigquery_storage_v1 import reader
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery_storage_v1/reader.py", line 28, in <module>
    import pandas
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 63, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 1, in init pandas._libs.tslibs.offsets
  File "<frozen importlib._bootstrap>", line 194, in _lock_unlock_module
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/data_ingestion_gcs_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 204
[2023-02-21 11:43:51,425] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2023-02-21 11:43:51,905] {processor.py:171} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 32.129 seconds
[2023-02-21 11:44:24,796] {processor.py:163} INFO - Started process (PID=235) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2023-02-21 11:44:24,945] {processor.py:642} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2023-02-21 11:44:25,052] {logging_mixin.py:109} INFO - [2023-02-21 11:44:25,051] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2023-02-21 11:44:55,141] {logging_mixin.py:109} INFO - [2023-02-21 11:44:55,139] {timeout.py:36} ERROR - Process timed out, PID: 235
[2023-02-21 11:44:55,597] {logging_mixin.py:109} INFO - [2023-02-21 11:44:55,188] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 10, in <module>
    from airflow.providers.google.cloud.operators.bigquery import BigQueryCreateExternalTableOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 38, in <module>
    from airflow.providers.google.cloud.hooks.bigquery import BigQueryHook, BigQueryJob
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 33, in <module>
    from google.cloud.bigquery import (
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/__init__.py", line 35, in <module>
    from google.cloud.bigquery.client import Client
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 61, in <module>
    from google.cloud.bigquery_storage_v1.services.big_query_read.client import (
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery_storage_v1/__init__.py", line 25, in <module>
    from google.cloud.bigquery_storage_v1 import client
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery_storage_v1/client.py", line 26, in <module>
    from google.cloud.bigquery_storage_v1 import reader
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery_storage_v1/reader.py", line 28, in <module>
    import pandas
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 20, in <module>
    from pandas.core.arrays.string_arrow import ArrowStringArray
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/string_arrow.py", line 65, in <module>
    import pyarrow.compute as pc
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/compute.py", line 239, in <module>
    _make_global_functions()
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/compute.py", line 236, in _make_global_functions
    g[cpp_name] = g[name] = _wrap_function(name, func)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/compute.py", line 215, in _wrap_function
    return _decorate_compute_function(wrapper, name, func, option_class)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/compute.py", line 88, in _decorate_compute_function
    cpp_doc = func._doc
  File "pyarrow/_compute.pyx", line 307, in pyarrow._compute.Function._doc.__get__
  File "<string>", line 1, in __new__
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/data_ingestion_gcs_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 235
[2023-02-21 11:44:56,316] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_gcs_dag.py
[2023-02-21 11:44:56,823] {processor.py:171} INFO - Processing /opt/airflow/dags/data_ingestion_gcs_dag.py took 32.474 seconds
[2023-02-21 11:45:30,183] {processor.py:163} INFO - Started process (PID=265) to work on /opt/airflow/dags/data_ingestion_gcs_dag.py
[2023-02-21 11:45:30,397] {processor.py:642} INFO - Processing file /opt/airflow/dags/data_ingestion_gcs_dag.py for tasks to queue
[2023-02-21 11:45:30,426] {logging_mixin.py:109} INFO - [2023-02-21 11:45:30,422] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_gcs_dag.py
